# This workflow will build a Node.js project and deploy it to GitHub Pages.

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Clean build environment (remove node_modules and dist)
        run: |
          rm -rf node_modules
          rm -rf dist

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      # --- Removed: The "Fix CSS Link in index.html for GitHub Pages" step is no longer needed. ---

      - name: Upload production-ready build artifacts for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # Specify the directory where your built files are located

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
