name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # This workflow runs when changes are pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use a fresh Ubuntu environment for each job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to checkout your repository code

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Action to set up Node.js environment
        with:
          node-version: '20' # Specify the Node.js version

      - name: Install dependencies
        run: npm install # Install project dependencies

      - name: Build project
        run: npm run build # Run the build command as defined in package.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Action to deploy to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub Token for authentication
          publish_dir: ./dist # The directory to publish (output of your build)
          # cname: example.com # Uncomment and replace with your custom domain if you have one